### PR TITLE
Alias Python API v3.7.0

### PR DESCRIPTION
**Pull request by staceyoue**
* Update Alias Python API for Alias < 2024.0
* Add python bindings for Alias C++ locators API
* Extend AlConstructionPlane python bindings
* Add Alias Python API for Python 3.10

### CODE REVIEW

**Comment by staceyoue** [comment]
> I'm not sure to understand what this is about here. There Alias versions use to use Python 3.7 and 3.9. And we now want them to use Python 3.10? Am I missing something?

@julien-lang depending on the SG Desktop version that is used to launch Alias, this will run the ShotGrid Alias Engine (tk-alias) with the Python version shipped with SG Desktop (e.g. SGD 1.7.3 == Python 3.7, SGD 1.8 == Python 3.9, SGD 1.9 == Python 3.10). Based on which Python version is running, tk-alias needs to use the Alias plugin and api files compiled with that specific Python version.

**Comment by julien-lang** [comment]
> depending on the SG Desktop version that is used to launch Alias, this will run the ShotGrid Alias Engine (tk-alias) with the Python version shipped with SG Desktop (e.g. SGD 1.7.3 == Python 3.7, SGD 1.8 == Python 3.9, SGD 1.9 == Python 3.10). Based on which Python version is running, tk-alias needs to use the Alias plugin and api files compiled with that specific Python version.

Ok, so why do you remove the files for Python 3.7 and 3.9? Does that mean the engine will not work anymore with SGD 1.7.x and 1.8.x?

**Comment by staceyoue** [comment]
> > depending on the SG Desktop version that is used to launch Alias, this will run the ShotGrid Alias Engine (tk-alias) with the Python version shipped with SG Desktop (e.g. SGD 1.7.3 == Python 3.7, SGD 1.8 == Python 3.9, SGD 1.9 == Python 3.10). Based on which Python version is running, tk-alias needs to use the Alias plugin and api files compiled with that specific Python version.
> 
> Ok, so why do you remove the files for Python 3.7 and 3.9? Does that mean the engine will not work anymore with SGD 1.7.x and 1.8.x?

We did not remove files for Python 3.7 and 3.9, we just updated them in this PR to the new version.

**Review by julien-lang — APPROVED** [review]
LGTM!

**Pull request merged**
