### PR TITLE
Remove unused  Alias distribution files.

### PR DESCRIPTION
**Pull request by staceyoue**
* Alias >= 2024 will always use Python 3.7 on the tk-framework-alias side, which means Alias Plugin/API compiled for Python 3.9 (for Alias >= 2024) will not be used
* Remove unused files to reduce toolkit bundle size (to improve bundle download speed)

### CODE REVIEW

**Review by julien-lang — COMMENTED** [review]
I like to see code removed while keeping the same features :)

However, I'm not sure to understand the statement:

> Alias >= 2024 will always use Python 3.7 on the tk-framework-alias side, which means Alias Plugin/API compiled for Python 3.9 (for Alias >= 2024) will not be used
> Remove unused files to reduce toolkit bundle size (to improve bundle download speed)


Could you explain a bit more about that please @staceyoue?
Like why Alias >= 2024 would use Py 3.7 and not a more recent version?

**Comment by staceyoue** [comment]
> Could you explain a bit more about that please @staceyoue? Like why Alias >= 2024 would use Py 3.7 and not a more recent version?

Alias 2024.0 ships Qt 5.15.0, which requires python < 3.9. So for simplicity and consistency, we use python 3.7 for Alias > 2024.

I'll also add that when I say "Alias 2024 will always use python 3.7", this only applies to tk-framework-alias.
The framework runs in the same process as Alias, so it needs to have a compatible python/PySide version with Alias. However, since the framework bootstraps the ShotGrid Alias Engine (tk-alias) in a separate process, tk-alias is free to use any python version, and will run with the python version shipped with SG Desktop.

**Review by julien-lang — APPROVED** [review]
LGTM! Thanks @staceyoue for the extra information.

**Review by carlos-villavicencio-adsk — APPROVED** [review]
:shipit:

**Pull request merged**
